### ISSUE TITLE
Can you provide configure settiings for SDK 4.3

### ISSUE THREAD

**Issue by batkov** [lajos/iFrameExtractor#3]
Hello lajos.
I have created iPhone app, that encodes images and sounds to video file. 
It works great at simulator, but not works at device. I think the issue in libraries.

I use libraries from your project. Can you help me? how to configure and build libs for sdk 4.3?

I have trying to change build_armv6, build_armv7 etc. (iPhoneOS4.1.sdk  to iPhoneOS4.3.sdk, but it has no effect)
Best redgards, Hariton Batkov

**Comment by jerrycn** [comment]
./configure --disable-doc --disable-ffmpeg --disable-ffplay --disable-ffserver --enable-cross-compile --arch=arm --target-os=darwin --cc=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc --as='gas-preprocessor/gas-preprocessor.pl /Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc' --sysroot=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.3.sdk --cpu=cortex-a8 --extra-cflags='-arch armv7' --extra-ldflags='-arch armv7 -isysroot /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.3.sdk' --enable-pic

./build_armv7
:)

**Comment by Macher** [comment]
@batkov  Hi batkov, can you upload your iPhone app, that encodes images and sounds to video file.

**Comment by batkov** [comment]
@Macher No. I can't. It is a proprietary app. Also it is not release yet. I will send you link to AppStore - it will be free app.

**Comment by Macher** [comment]
@batkov 
Thanks batkov, im also able to encode the video from images

**Comment by PShantanu** [comment]
@batkov @Macher :Can u help me with iFrameExtractor.I am trying to run it on Simulator using Xcode 4.2 but no success.I have follwed all given steps but getting error saying " "_avcodec_decode_video2", referenced from:
      -[VideoFrameExtractor stepFrame] in VideoFrameExtractor.o"

**Comment by neowinston** [comment]
Hi Lajos,

I've been able to compile a fat binary for armv6, armv7, armv7s and i386 with your instructions and the video plays perfectly! Thanks for your shared code! I'd like to have sound in my application. How can I do that? Thanks for time!
